# GZCore Configuration
# Set to true/false to enable/disable plugins
plugins:
  "DeviceACM": true
  "EconomyAPI.PM5": true
  "FormAPI": true
  "DEVirion-PM5": true
  "HealAndFeed": true
  "HitParticle": true
  "MultiWorld": true
  "InvMenu_dev-195": true
  "PocketMine-DevTools": true
  "ScoreHud": true